sudo: required
language: node_js
node_js:
  - "14"

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify
    - npm run cy:info

script:
  - npm install
  - echo $pwd
  # - npm run start:ci &
  # - npm run cy:run -- --record --parallel --group $STAGE_NAME
  - npm run cy:run -- --spec "cypress/integration/simpletest.spec.js"
